name: debugger-action
on:
  push:
    branches:
      - debugger-action
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Debug session12
        uses: chousann/debugger-action@master
      - name: Run a multi-line script
        run: |
          unset TMUX
          tmux attach
          tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}'
