name: debugger-action
on:
  push:
    branches:
      - debugger-action
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Debug session13
        uses: chousann/debugger-action@master
      - name: tmate sleep
        run: bash ./tmt.sh
